### ISSUE TITLE
Trino container not running on mac M2 2023

### ISSUE THREAD

**Issue by Parva-Github** [josephmachado/analytical_dp_with_sql#5]
Hi, i followed the steps to run the docker container on mac m2 ,after make up command  I cannot enter into trino cli.

When i looked up for the running containers i found that trino and minio containers are not running.

I opened up the logs for the trino container and found this below error message

---

2023-03-06T16:59:22.514Z	ERROR	main	io.trino.server.Server	No factory for connector 'hive_hadoop2'.  Available factories: [hive, ignite, delta_lake, memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, elasticsearch, jmx, postgresql, redshift, sqlserver, localfile, example_http, tpch, iceberg, mysql, bigquery, prometheus, mongodb, pinot, tpcds, hudi, oracle, mariadb, druid, cassandra, clickhouse, kafka, singlestore, atop, raptor_legacy, trino_thrift, phoenix5]
java.lang.IllegalArgumentException: No factory for connector 'hive_hadoop2'.  Available factories: [hive, ignite, delta_lake, memory, kudu, blackhole, kinesis, redis, accumulo, gsheets, elasticsearch, jmx, postgresql, redshift, sqlserver, localfile, example_http, tpch, iceberg, mysql, bigquery, prometheus, mongodb, pinot, tpcds, hudi, oracle, mariadb, druid, cassandra, clickhouse, kafka, singlestore, atop, raptor_legacy, trino_thrift, phoenix5]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435)
	at io.trino.connector.DefaultCatalogFactory.createCatalog(DefaultCatalogFactory.java:118)
	at io.trino.connector.LazyCatalogFactory.createCatalog(LazyCatalogFactory.java:45)
	at io.trino.connector.StaticCatalogManager.lambda$loadInitialCatalogs$1(StaticCatalogManager.java:158)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
	at io.trino.connector.StaticCatalogManager.loadInitialCatalogs(StaticCatalogManager.java:152)
	at io.trino.server.Server.doStart(Server.java:142)
	at io.trino.server.Server.lambda$start$0(Server.java:90)
	at io.trino.$gen.Trino_409____20230306_165916_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:90)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)

2023-03-06T16:59:22.514Z	INFO	Thread-76	io.airlift.bootstrap.LifeCycleManager	JVM is shutting down, cleaning up
2023-03-06T16:59:22.514Z	INFO	Thread-76	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2023-03-06T16:59:22.514Z	INFO	Thread-76	io.airlift.bootstrap.LifeCycleManager	Life cycle stopped
parvatheesamputikalapudi@parvathesamsMBP analytical_dp_with_sql %

**Comment by josephmachado** [comment]
Hi @Parva-Github Can you please do a `git pull` and try it again? I've [merged a fix](https://github.com/josephmachado/analytical_dp_with_sql/pull/7). Thank you for pointing this out in our discussion.

If this works, please close the issue, else lmk.

**Comment by josephmachado** [comment]
Closing the issue due to inactivity
@Parva-Github Please reopen if the issue persists.
